# Site
name: "Everything CRM"
description: "just a simple guy, sharing his thoughts and views on the Dynamics 365 Platform"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'everythingcrm'
email: 'ppaliwal.89@gmail.com'
mailchimp-list: 'https://everythingcrm.us19.list-manage.com/subscribe/post?u=19ec8dca0b80466e068c16816&amp;id=430d3c0c76'

include: ["_pages"]
permalink: /:categories/:year/:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-assets
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: piyush
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

assets:
  compress:
    css: true
    js: true
  gzip: true
  

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]